// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiMapScraper.Web.Data;

#nullable disable

namespace WikiMapScraper.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708135910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("WikiMapScraper.Web.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("WikiPageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WikiPageId")
                        .IsUnique();

                    b.ToTable("Places");
                });

            modelBuilder.Entity("WikiMapScraper.Web.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("WikiMapScraper.Web.Models.TopicPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TopicId", "PlaceId")
                        .IsUnique();

                    b.ToTable("TopicPlaces");
                });

            modelBuilder.Entity("WikiMapScraper.Web.Models.TopicPlace", b =>
                {
                    b.HasOne("WikiMapScraper.Web.Models.Place", "Place")
                        .WithMany("TopicPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiMapScraper.Web.Models.Topic", "Topic")
                        .WithMany("TopicPlaces")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WikiMapScraper.Web.Models.Place", b =>
                {
                    b.Navigation("TopicPlaces");
                });

            modelBuilder.Entity("WikiMapScraper.Web.Models.Topic", b =>
                {
                    b.Navigation("TopicPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
